[project]
name = "promptlibz"
version = "0.1.4"
description = "用来存储优质prompt的仓库"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dill>=0.4.0",
    "llama-index>=0.12.31",
    "pandas>=2.2.3",
    "pytest>=8.3.5",
    "pytest-html>=4.1.1",
    "pyyaml>=6.0.2",
]
